# It's my Jupyter Notebook about NumPy

## Lesson01

**Документация**: https://numpy.org/doc/stable/user/index.html#user

### Импорт библиотеки

In [1]:
import numpy as np

### Создание массива/двумерного массива

**Создание одномерного массива**

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Одно из самых важных свойств массива: все элементы в нём должны быть **одного типа**.

In [4]:
np.array([1.2, 3.4, 5, 6, 7, 8, 9])

array([1.2, 3.4, 5. , 6. , 7. , 8. , 9. ])

In [5]:
np.array([11, 234.5, "hello"])

array(['11', '234.5', 'hello'], dtype='<U32')

```np.fromiter()``` — это функция, которая создаёт массив из итерируемого объекта (итератора), не создавая сначала промежуточный список. Это полезно для эффективного использования памяти, особенно при работе с большими данными.  
Синтаксис: ```np.fromiter(iterable, dtype, count=-1)```  
* ```iterable``` — любой итерируемый объект (например, генератор или итератор).
* ```dtype``` — тип данных элементов массива (например, np.int32, np.float64).
* ```count``` (необязательный) — количество элементов для чтения (по умолчанию -1, что означает чтение всех доступных).

In [6]:
np.fromiter(map(int, ["1", "2", "3", "4"]), dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

**Формируем массив из строки чисел, указывая разделитель**

In [7]:
np.fromstring("1, 3, 4, 5, 120", sep=",")

array([  1.,   3.,   4.,   5., 120.])

**Каждый элемент элемент массива вычисляется по функции**

In [8]:
np.fromfunction(lambda x, y: x**2 + y**2, (3, 5), dtype=np.int8)

array([[ 0,  1,  4,  9, 16],
       [ 1,  2,  5, 10, 17],
       [ 4,  5,  8, 13, 20]], dtype=int8)

**Создание двумерного массива**

In [9]:
np.array([[1, 2, 3], [4.9, 5, 6]])

array([[1. , 2. , 3. ],
       [4.9, 5. , 6. ]])

### Как узнать тип данных в массиве? dtype

In [10]:
np.array([1, 2, 3, 4, 5]).dtype

dtype('int64')

In [11]:
np.array([1.2, 3.4, 5, 6, 7, 8, 9]).dtype

dtype('float64')

### Как измерить длину массива? len() shape ndim

В случае с одномерным массивом всё понятно, функция ```len()``` выведет количество элементов в нём.

In [12]:
arr = np.array([1, 2, 3, 4, 5])
len(arr)

5

Функция ```len()``` для двумерного массива выведет нам количество вложенных в него элементов. В нашем случае в ```arr2``` вложено 2 элемента, которые в свою очередь также являются массивами.

In [13]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
len(arr2)

2

А если мы хотим узнать больше про наш двумерный массив? С этим нам поможет метод ```shape```. Он возвращает кортеж, где первый элемент отвечает за количество вложенных массивов, а второй за количество элементов в каждом из них.

In [14]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape

(2, 3)

Хотя на самом деле ```shape``` показывает, насколько глубок массив и сколько элементов на каждом из уровней. Пусть ```n``` - длина кортежа, получаемого на выходе при использовании метода ```shape```. Тогда мы можем говорить о том, что массив будет ```n```-мерным.

In [15]:
arr3 = np.array([[[1], [2]], [[3], [4]], [[5], [6]]])
arr3.shape

(3, 2, 1)

In [16]:
arr4 = np.array([[[[1], [2], [3]], [[4], [5], [6]]], [[[7], [8], [9]], [[10], [11], [12]]], [[[13], [14], [15]], [[16], [17], [18]]]])
arr4.shape

(3, 2, 3, 1)

Чтобы не исхищряться и не смотреть на длину кортежа, получаемого при использовании метода ```shape``` лучше использовать метод ```ndim```.

In [17]:
arr4 = np.array([[[[1], [2], [3]], [[4], [5], [6]]], [[[7], [8], [9]], [[10], [11], [12]]], [[[13], [14], [15]], [[16], [17], [18]]]])
arr4.ndim

4

In [18]:
arr4.ndim == len(arr4.shape)

True

### Как заполнить массив/матрицу произвольными значениями? full()

Прочитав предыдущий пункт, у многих закономерно возник вопрос: "*А как заполнить массив произвольными значениями?*"

Легко, используем функцию **full()**. В качестве первого аргумента передадим размер, а в качестве второго - то, чем будем заполнять массив.

In [23]:
array_full_of_fives = np.full(10, 5)
array_full_of_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

В случае, если мы захотим создать матрицу, то в качестве первого аргумента передадим кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов.

In [24]:
matrix_full_of_nines = np.full((4, 5), 9)  # 4 строки и 5 столбцов
matrix_full_of_nines

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

### Как создать массив, который будет заполнен значениями от 0 до N? arange()

Функция **arange()**. По сути тот же range() только для массивов в numpy.

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Точно так же, как и в range(), в **arange()** можно задавать ```(start, finish, step)```.

In [26]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Lesson02

### Как задать тип данных? dtype astype()

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

А что если я хочу, чтобы у меня были не целые числа, а с плавающей запятой? Тогда нужно дописать параметр **dtype=**.

In [28]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

А что если у нас уже есть массив, и мы хотим, чтобы все значения в нём снова стали *int*?
Для этого существует функция **astype()**. В аргумент функции передаётся тот тип данных, который мы желаем.

In [29]:
arr = arr.astype(np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

<b>*Важное замечание!*</b> Сама по себе функция *astype()* не меняет значение массива, а возвращает его копию с изменённым типом данных, поэтому нужно куда-то сохранять копию массива.

In [30]:
arr.astype(np.float64)
arr

array([1, 2, 3, 4, 5], dtype=int32)

Если вы поменяете тип данных с **float_ на int_**, то numpy отрежет десятичную часть от каждого числа и оставит только целую. В целом, нормальное и типичное поведение для питона.

In [31]:
arr = np.array([1.01, 9.99, 4.5, 6.45, 7.8,])
arr

array([1.01, 9.99, 4.5 , 6.45, 7.8 ])

In [32]:
arr = arr.astype(np.int32)
arr

array([1, 9, 4, 6, 7], dtype=int32)

### Математические операции с массивами

В отличие от списков в питоне, математические операции касательно массивов работают иначе. Все ниже перечисленные операции показаны на массивах, но матрицах тоже работают.

**Умножение**

In [33]:
lst = [1, 2, 3, 4]
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [34]:
arr = np.array([1, 2, 3, 4])
arr * 2

array([2, 4, 6, 8])

In [35]:
arr * arr

array([ 1,  4,  9, 16])

**Сложение и вычитание**

In [36]:
arr + 10

array([11, 12, 13, 14])

In [37]:
10 - arr

array([9, 8, 7, 6])

**Деление**

In [38]:
arr / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
arr // 2

array([0, 1, 1, 2])

In [40]:
arr % 2

array([1, 0, 1, 0])

При делении на ноль вылезает ```inf```.

In [41]:
m1 = np.array([1, 2])
m2 = np.array([0, 4])
m3 = m1 / m2
m3

C:\Users\OL\AppData\Local\Temp\ipykernel_16952\254973887.py:3: RuntimeWarning: divide by zero encountered in divide
  m3 = m1 / m2


array([inf, 0.5])

Чтобы выявлять такие моменты, существует функция **isinf()**.

In [42]:
np.isinf(m3)

array([ True, False])

**Возведение в степень**

In [43]:
arr ** 3

array([ 1,  8, 27, 64])

In [44]:
arr ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

**Извлечение корня**

In [45]:
arr = np.array([1, 4, 9, 16, 25, 36])
np.sqrt(arr)

array([1., 2., 3., 4., 5., 6.])

**Модуль**

In [46]:
arr = np.array([1, -2, 3, -4, 5, -6])
np.abs(arr)

array([1, 2, 3, 4, 5, 6])

**Математическое округление**

In [47]:
arr = np.array([3.49, 5.6, 4.45, 2.66])
np.round(arr, 1)  # Округление до ближайшего чётного. 2-ой параметр - количество знаков после запятой.

array([3.5, 5.6, 4.4, 2.7])

**Округление вверх**

In [48]:
arr = np.array([3.49, 5.6, 4.45, 2.66, 9.01])
np.ceil(arr)

array([ 4.,  6.,  5.,  3., 10.])

**Округление вниз**

In [49]:
arr = np.array([3.49, 5.6, 4.45, 2.66, 9.01, 99.99])
np.floor(arr)

array([ 3.,  5.,  4.,  2.,  9., 99.])

### Сравнение массивов

Numpy сравнивает массивы поэлементно

In [50]:
#  Резульаты измерений температуры в 1-й и 2-й дни
first_day = np.array([36.6, 36.5, 36.8])
second_day = np.array([36.6, 36.6, 36.6])
first_day > second_day

array([False, False,  True])

### Срезы

Срезы в numpy делаются абсолютно так же, как при работе со списками в python при помощи ```[start:finish:step]```.

In [51]:
arr = np.arange(10)
first_half = arr[:5]
second_half = arr[5:]
first_half, second_half

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

При использовании срезов, если границы выходят за размеров массива, то ошибки ```IndexError``` не будет возникать. Вместо этого будет взят максимально возможный срез в данной ситуации.

In [52]:
x = arr[0:200]  # явно выходим за  границы массива
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***Важный момент!*** Если мы захотим переприсвоить значение среза, то изменится изначальный массив.

In [53]:
first_half[0] = 100
second_half[1] = 101
arr

array([100,   1,   2,   3,   4,   5, 101,   7,   8,   9])

Что же делать, чтобы изначальный массив не изменялся? Читаем следующий блок ;)

### Как создать копию массива? copy()

Чтобы создать копию массива, достаточно использовать функцию **copy()**.

In [54]:
arr = np.arange(10)
first_half = arr[:5].copy()
second_half = arr[5:].copy()
first_half, second_half

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [55]:
first_half[0] = 100
second_half[1] = 101
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Мы изменили значение **копии** среза, а не сам срез, поэтому изначальный массив не поменялся.

## Lesson03

### Индексация двумерных массивов

К элементам двумерного массива мы можем обращаться как мы обращаемся к двумерным спискам, но есть более короткая запись. Numpy позволяет в одних квадратных скобках через запятую указать нужные нам индексы.

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
elem_1 = arr[1][1]
elem_2 = arr[1, 1]
elem_1 == elem_2

np.True_

Если вытаскивать строки и отдельные элементы довольно легко, то как нам вытащить столбцы?

Для этого мы у всего у массива возьмём по нулевому элементу. То есть двоеточие говорит нам о том, что бы берём все строки, а 0 о том, что у каждой строки мы берём нулевой элемент.

In [57]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [58]:
arr2[:, 0]

array([ 1,  5,  9, 13, 17])

Что примечательно, многие из читающих могут подумать, а почему мы не можем написать просто ```arr2[:][0]```?

In [59]:
arr2[:][0]

array([1, 2, 3, 4])

Подвох в том, что это особенность синтаксиса numpy. Конструкция ```arr2[:, 0]``` выполняется построчно, а ```arr2[:][0]``` - нет.

In [60]:
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [61]:
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

По примерам выше уже можно было понять, что общий синтаксис выглядить следующим образом:  
**```arr[срез по нужным строкам, срез по нужным стобцам]```**

### Фильтрация с помощью булевой маски

**Булева маска** - это массив из значений True и False. Каждый элемент проходит фильтрацию через булеву маску и распределяется в зависимости от значения маски:  
*  Если на той же позиции в маске стоит значение True, элемент добавляется в итоговый массив
*  Если на позиции стоит значение False, то элемент не будет включен в итоговый массив

In [62]:
arr = np.arange(10)
mask = np.array([True, True, True, False, False, False, False, False, True, True])
arr[mask]

array([0, 1, 2, 8, 9])

**Создание маски по условию**

Чтобы применить булеву маску к исходному массиву, достаточно подставить ее в качестве индекса.

In [63]:
compare_mask = arr < 3
compare_mask

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [64]:
arr[compare_mask]

array([0, 1, 2])

Чаще всего мы просто сразу пишем условие в квадратных скобках.

In [65]:
arr[arr > 5]

array([6, 7, 8, 9])

**Инверсия булевого массива**

Если мы захотим в маске поменять все значения с True на False, а с False на True, то нужно сделать инверсию маски. Для этого существует специальный символ тильда ```~```.

In [66]:
mask = np.array([True, False, False, True])
~mask

array([False,  True,  True, False])

**Алгебра логики булевых массивов**

In [67]:
mask_1 = np.array([True, False, False])
mask_2 = np.array([True, True, False])

*Логическое И(&)*

In [68]:
mask_1 & mask_2

array([ True, False, False])

*Логическое ИЛИ(|)*

In [69]:
mask_1 | mask_2

array([ True,  True, False])

### Прихотливая индексация

In [70]:
arr = np.array([
               [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16],
               [17, 18, 19, 20]
              ])

Интересное наблюдение: ```arr[[0, 2], :]``` и ```arr[[0, 2]]``` дают одинаковый вывод, порядок строк не важен.

In [71]:
arr[[0, 2], :] == arr[[0, 2]]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
arr[[4, 1]]

array([[17, 18, 19, 20],
       [ 5,  6,  7,  8]])

Аналогично работает и с колонками. Допустим, что мы хотим вытащить 2 и 3 столбец, причем поменять их местами.

In [73]:
arr[:, [2, 1]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18]])

**Задача.** На вход функции подается двумерный массив: доработайте функцию так, чтобы она вернула значения, которые лежат на главной диагонали. Значения должны быть в одномерном массиве.

In [74]:
def solution(arr):
    arr = arr[range(5), range(5)]
    return arr

### Преобразование одномерного массива в двумерный и наоборот. reshape()

Чтобы преобразовать одномерный массив в двумерный существует функция **reshape()**. В качестве аргумента ей передаётся кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов. Самое главное — при использовании функции reshape() произведение ее параметров
должно быть равно количеству элементов в массиве.

In [75]:
arr = np.arange(50)
arr.reshape((5, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Чтобы преобразовать двумерный массив в одномерный, в качестве аргумента в reshape() передаётся -1.

In [76]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

*Функция reshape() именяет исходный массив, а не делает его копию.*

## Lesson04

### NaN

```NaN``` (Not a Number) – специальное значение, обозначающее неопределенные или некорректные числовые данные. Оно часто появляется в результате недопустимых математических операций, например:

In [77]:
np.log(-1)

C:\Users\OL\AppData\Local\Temp\ipykernel_16952\153577755.py:1: RuntimeWarning: invalid value encountered in log
  np.log(-1)


np.float64(nan)

In [78]:
arr = np.array([2, np.nan, 4, 1, np.nan])
arr

array([ 2., nan,  4.,  1., nan])

NaN портит вычисления:

In [79]:
np.nan + 10

nan

In [80]:
np.nan * 0

nan

In [81]:
np.mean([1, 2, np.nan, 4])

np.float64(nan)

Функция **isnan()** проверяет, какие элементы массива являются NaN и возвращает булевый массив.

In [82]:
np.isnan(arr)

array([False,  True, False, False,  True])

### Как присвоить без присвоения. out=

In [83]:
arr = np.array([1, -2, -3, 4, 5])
arr

array([ 1, -2, -3,  4,  5])

In [84]:
np.abs(arr)

array([1, 2, 3, 4, 5])

In [85]:
arr

array([ 1, -2, -3,  4,  5])

Как мы видим, результат функции abs() не сохранился. Можно сохранить обычным присваиванием, а можно с помощью параметра **out=**. В параметр мы передаём имя переменной, в которую мы хотим сохранить результат. Параметр **работает** для любой функции.

In [86]:
np.abs(arr, out=arr)

array([1, 2, 3, 4, 5])

In [87]:
arr

array([1, 2, 3, 4, 5])

***Важное замечание!*** Переменная, которую мы передаём в параметр должна быть определена.

### Унарные и бинарные функции

Функции, которые принимают на вход 1 массив называются - **унарными**.  
Функции, которые принимают на вход 2 массива называются - **бинарными**.

До этого мы работали с унарными функциями, теперь поговорим о бинарных.

In [88]:
first = np.array([1, 2, 7, 9])
second = np.array([0, 3, 5, 10])

In [89]:
np.maximum(first, second)  # сравнивает поэлементно и кладёт максимум

array([ 1,  3,  7, 10])

In [90]:
np.minimum(first, second)  # сравнивает поэлементно и кладёт минимум

array([0, 2, 5, 9])

In [91]:
np.add(first, second)  # поэлементно складывает и кладёт сумму

array([ 1,  5, 12, 19])

In [92]:
np.subtract(first, second)  # поэлементно вычитает и кладёт разность

array([ 1, -1,  2, -1])

In [93]:
np.multiply(first, second)  # поэлементно умножает и кладёт произведение

array([ 0,  6, 35, 90])

In [94]:
div = np.divide(first, second)  # поэлементно делит и кладёт частное
div

C:\Users\OL\AppData\Local\Temp\ipykernel_16952\2825760164.py:1: RuntimeWarning: divide by zero encountered in divide
  div = np.divide(first, second)  # поэлементно делит и кладёт частное


array([       inf, 0.66666667, 1.4       , 0.9       ])

In [95]:
np.isinf(div)

array([ True, False, False, False])

In [96]:
np.greater(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 > значения из 2, иначе - False

array([ True, False,  True, False])

In [97]:
np.greater_equal(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 >= значения из 2, иначе - False

array([ True, False,  True, False])

In [98]:
np.less(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 < значения из 2, иначе - False

array([False,  True, False,  True])

In [99]:
np.less_equal(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 <= значения из 2, иначе - False

array([False,  True, False,  True])

In [100]:
np.equal(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 = значения из 2, иначе - False

array([False, False, False, False])

In [101]:
np.not_equal(first, second)  # поэлементно сравнивает и возвращает True, если значение из 1 != значения из 2, иначе - False

array([ True,  True,  True,  True])

## Lesson05

### Логические функции. where()

Мы можем использовать функцию **where()** для выбора элементов из массива на основе условия.

Синтаксис следующий ```np.where(условие, x, y)```.  
* x — значения, возвращаемые, если условие True.
* y — значения, возвращаемые, если условие False.

In [102]:
arr = np.array([-1, -2, -3, 1, 2, 3])
np.where(arr > 0, 1, 0)

array([0, 0, 0, 1, 1, 1])

Чтобы положить значение элемента в результирующий массив, надо указать массив в качестве одного из аргументов.

In [103]:
np.where(arr > 0, arr ** 2, arr)

array([-1, -2, -3,  1,  4,  9])

Если аргументы x и y не указаны, метод вернет индексы элементов, удовлетворяющих условию.

In [104]:
np.where(arr > 0)

(array([3, 4, 5]),)

### Математические и статистические функции

In [105]:
arr = np.arange(6)

In [106]:
np.sum(arr)  # Сумма

np.int64(15)

При применении суммы к массиву булевых значений, numpy отождествляет True с 1, а False с 0.

In [107]:
bool_arr = [True, False, True, False, False]
np.sum(bool_arr)

np.int64(2)

In [108]:
np.mean(arr)  # Среднее арифметическое

np.float64(2.5)

In [109]:
np.min(arr)  # Минимум

np.int64(0)

In [110]:
np.max(arr)  # Максимум

np.int64(5)

In [111]:
np.std(arr)  # Стандартное отклононение

np.float64(1.707825127659933)

In [112]:
np.var(arr)  # Вычисление дисперсии

np.float64(2.9166666666666665)

In [113]:
np.argmin(arr)  # Индекс минимального значения

np.int64(0)

In [114]:
np.argmax(arr)  # Индекс максимального значения

np.int64(5)

### Упрощенная запись при использовании функций

Порядком надоедает обращаться каждый раз к numpy и писать ```np.функция(аргумент_функции)```.  
Вместо этого есть другая форма записи: ```аргумент_функции.функция()```.

In [115]:
arr = np.arange(6)
arr.mean()

np.float64(2.5)

### Обработка строк и столбцов в матрице. axis=

In [116]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
arr.sum()

np.int64(45)

А если мы хотим узнать сумму(или любую другую статистику) в каждой строке и в каждом столбце? Для этого существует параметр **axis=**.  
* ```axis=1``` - отработает по строкам,
* ```axis=0``` - отработает по столбцам.
Результат будет в отдельном массиве. 

In [118]:
arr.mean(axis=1)  # по строкам

array([2., 7.])

In [119]:
arr.mean(axis=0)  # по столбцам

array([2.5, 3.5, 4.5, 5.5, 6.5])

*Если есть сомнения, какую ось указать, то подумаем по какому измерению мы бы сделали цикл для поиска статистического значения. Или другими словами, какое измерение мы "свертываем" в статистическую функцию.*

## Lesson06

### np.random

**Генерация рандомных целых чисел**

* первый параметр ```start,step, finish```,
* второй параметр ```size=``` задаёт размер массива, который мы заполняем.

In [120]:
arr = np.random.randint(10, 20, size=10)
arr

array([13, 19, 19, 10, 14, 19, 15, 15, 16, 19], dtype=int32)

**Генерация уникальных рандомных целых чисел**

По сути, функция ```permutation()``` просто перемешивает все целые значения в промежутке ```[0, n)```. Т.е. в списке у нас хранятся уникальные значения.

In [121]:
arr = np.random.permutation(20)
arr

array([16, 19, 11,  3,  6,  4, 17,  5,  8, 13, 14, 15,  9,  1,  2,  0,  7,
       18, 10, 12], dtype=int32)

**Генерация матрицы с рандомными числами**

In [122]:
np.random.randint(1, 15, size=(2, 5))

array([[10, 12, 14,  1,  7],
       [13,  4, 14, 13, 12]], dtype=int32)

**Перемешка значений в массиве**

In [123]:
arr = np.random.randint(40, size=10)
arr

array([16, 38, 29,  3, 30, 28, 26, 18, 24,  9], dtype=int32)

In [124]:
np.random.shuffle(arr)
arr

array([ 9, 30,  3, 28, 38, 18, 26, 16, 24, 29], dtype=int32)

**Генерация случайных вещественных чисел**

In [125]:
np.random.rand(10)

array([0.57176402, 0.1507003 , 0.95968898, 0.37664669, 0.51871108,
       0.99460056, 0.48893563, 0.85904626, 0.49947182, 0.05713032])

In [126]:
np.random.randn(10)

array([-1.51082683, -0.01869678,  0.25441112, -0.8462642 ,  0.0413609 ,
        0.31590588,  2.35354919, -0.24409079,  1.50712515, -0.13013769])

**Генерация чисел в матрице**

In [127]:
np.random.randn(2, 5)

array([[-0.52538544,  0.91330462,  1.78361882, -1.35112272,  1.42401917],
       [ 0.90482458, -0.07437604,  0.81771548, -0.9263579 , -0.89684937]])

### Сортировка. sort()

Метод ```sort()``` изменяет уже существующий массив и сортирует его по возрастанию.

In [128]:
arr = np.random.randint(10, size=10)
arr

array([5, 0, 8, 0, 4, 9, 1, 3, 4, 9], dtype=int32)

In [129]:
arr.sort()
arr

array([0, 0, 1, 3, 4, 4, 5, 8, 9, 9], dtype=int32)

### Фильтрация массива по уникальным значения. uniqe()

Допустим, что у нас есть массив, хранящий список имён, и нам нужно вывести только те имена, которые в нём не повторяются.  
Для этого используем функцию **unique()**.

In [130]:
arr = np.array(['Andrey', 'Ivan', 'Oleg', 'Boris', 'Andrey'])
np.unique(arr)

array(['Andrey', 'Boris', 'Ivan', 'Oleg'], dtype='<U6')

У этой функции есть полезный аргумент **return_counts=**. Он возвращает количество раз, которое каждый уникальный элемент появляется в массиве.

In [131]:
unique_names = np.unique(arr, return_counts=True)
unique_names

(array(['Andrey', 'Boris', 'Ivan', 'Oleg'], dtype='<U6'), array([2, 1, 1, 1]))

С его помощью можно вывести список дублирующихся элементов.

In [132]:
count = unique_names[1]
names = unique_names[0]
names[count > 1]

array(['Andrey'], dtype='<U6')

### Проверка наличия элементов одного массива в другом. isin()

Чтобы проверить наличие элементов одного массива в другом существует функция **isin()**, которая вернёт булев массив.

In [133]:
arr1 = np.array(['Andrey', 'Ivan', 'Oleg', 'Boris', 'Andrey'])
arr2 = ['Oleg', 'Andrey']
np.isin(arr1, arr2)

array([ True, False,  True, False,  True])

На этом примере:  
* Andrey из ```arr1``` есть в ```arr2``` - True  
* Ivan из ```arr1``` нет в ```arr2``` - False  
* Oleg из ```arr1``` есть в ```arr2``` - True  
* Boris из ```arr1``` нет в ```arr2``` - False  
* Andrey из ```arr1``` есть в ```arr2``` - True

### Линейная алгебра

**Нулевая и единичная матрица**

In [20]:
zero_matrix = np.zeros((2, 3))  # 2 строки и 3 столбца
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
ones_matrix = np.ones((2, 3))  # 2 строки и 3 столбца
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

**Транспонирование**

In [134]:
a = np.array([[1, 5, 0], [6, 2, 0], [-2, 4, 8]])
a

array([[ 1,  5,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

In [135]:
a.T

array([[ 1,  6, -2],
       [ 5,  2,  4],
       [ 0,  0,  8]])

In [136]:
a.transpose()

array([[ 1,  6, -2],
       [ 5,  2,  4],
       [ 0,  0,  8]])

**Произведение матриц**

In [137]:
np.dot(a, a.T)

array([[26, 16, 18],
       [16, 40, -4],
       [18, -4, 84]])

**Определитель**

In [138]:
np.linalg.det(a)

np.float64(-224.00000000000014)

**Обратная матрица**

In [139]:
np.linalg.inv(a)

array([[-0.07142857,  0.17857143,  0.        ],
       [ 0.21428571, -0.03571429,  0.        ],
       [-0.125     ,  0.0625    ,  0.125     ]])

**Главная диагональ**

In [140]:
np.diag(a)

array([1, 2, 8])

**Верхний треугольник**

In [141]:
np.triu(a)

array([[1, 5, 0],
       [0, 2, 0],
       [0, 0, 8]])

**Нижний треугольник**

In [142]:
np.tril(a)

array([[ 1,  0,  0],
       [ 6,  2,  0],
       [-2,  4,  8]])

**Сумма главной диагонали**

In [143]:
np.trace(a)

np.int64(11)

**Поворот на 90 градусов вправо и влево**

In [144]:
np.rot90(a)

array([[ 0,  0,  8],
       [ 5,  2,  4],
       [ 1,  6, -2]])

In [164]:
np.rot90(a, -1)

array([[-2,  6,  1],
       [ 4,  2,  5],
       [ 8,  0,  0]])

## Lesson07

### Функции any() и all()

В numpy функции ```any``` и ```all``` используются для проверки элементов массива на истинность. Они работают аналогично встроенным функциям Python any() и all(), но могут работать по определённым осям массива.

**any**

Проверяет, есть ли **хотя бы один** True (или ненулевой элемент) в массиве.

In [145]:
arr = np.array([[0, 1, 0], [0, 0, 0]])
arr

array([[0, 1, 0],
       [0, 0, 0]])

In [146]:
np.any(arr)  # True, так как хотя бы один элемент ненулевой

np.True_

In [147]:
np.any(arr, axis=0)  # проверка по столбцам

array([False,  True, False])

In [148]:
np.any(arr, axis=1)  # проверка по строкам

array([ True, False])

**all**

Проверяет, являются ли **все** элементы массива True (ненулевыми).

In [149]:
arr = np.array([[1, 1, 1], [1, 0, 1]])
arr

array([[1, 1, 1],
       [1, 0, 1]])

In [150]:
np.all(arr)  # False, так как есть хотя бы один 0

np.False_

In [151]:
np.all(arr, axis=0)  # проверка по столбцам

array([ True, False,  True])

In [152]:
np.all(arr, axis=1)  # проверка по строкам

array([ True, False])

### Работа с файлами

In [153]:
arr = np.array([0, 1, 2, 3, 4])

**Запись в файл**

In [154]:
np.save('my file', arr)

**Чтение из файла**

In [155]:
np.load('my file.npy')

array([0, 1, 2, 3, 4])

**Как записать несколько массивов в файл и прочитать**

In [156]:
arr1 = np.array([0, 1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8, 9])

In [157]:
np.savez('arrays', key1=arr1, key2=arr2)

In [158]:
dict = np.load('arrays.npz')
dict

NpzFile 'arrays.npz' with keys: key1, key2

In [159]:
dict.files

['key1', 'key2']

In [160]:
dict['key1']

array([0, 1, 2, 3, 4])

In [161]:
dict['key2']

array([5, 6, 7, 8, 9])

**Как сжать файл**

In [162]:
np.savez_compressed('compressed', col1=arr1, col2=arr2)

In [163]:
np.load('compressed.npz')

NpzFile 'compressed.npz' with keys: col1, col2