# Lesson01

**Документация**: https://numpy.org/doc/stable/user/index.html#user

## Импорт библиотеки

In [1]:
import numpy as np

## Создание массива/двумерного массива

**Создание одномерного массива**

In [2]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

Одно из самых важных свойств массива: все элементы в нём должны быть **одного типа**.

In [3]:
lst_float = [1.2, 3.4, 5, 6, 7, 8, 9]
arr_float = np.array(lst_float)
arr_float

array([1.2, 3.4, 5. , 6. , 7. , 8. , 9. ])

**Создание двумерного массива**

In [4]:
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
lst2_float = [[1, 2, 3], [4.9, 5, 6]]
arr2_float = np.array(lst2_float)
arr2_float

array([[1. , 2. , 3. ],
       [4.9, 5. , 6. ]])

## Как узнать тип данных в массиве? dtype

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr_float.dtype

dtype('float64')

## Как измерить длину массива? len() shape ndim

В случае с одномерным массивом всё понятно, функция **len()** выведет количество элементов в нём.

In [8]:
arr = np.array([1, 2, 3, 4, 5])
len(arr)

5

Функция len() для двумерного массива выведет нам количество вложенных в него элементов. В нашем случае в ```arr2``` вложено 2 элемента, которые в свою очередь также являются массивами.

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
len(arr2)

2

А если мы хотим узнать больше про наш двумерный массив? С этим нам поможет метод **shape**. Он возвращает кортеж, где первый элемент отвечает за количество вложенных массивов, а второй за количество элементов в каждом из них.

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape

(2, 3)

Хотя на самом деле shape показывает, насколько глубок массив и сколько элементов на каждом из уровней. Пусть n - длина кортежа, получаемого на выходе при использовании метода shape. Тогда мы можем говорить о том, что массив будет n-мерным.

In [11]:
arr3 = np.array([[[1], [2]], [[3], [4]], [[5], [6]]])
arr3.shape

(3, 2, 1)

In [12]:
arr4 = np.array([[[[1], [2], [3]], [[4], [5], [6]]], [[[7], [8], [9]], [[10], [11], [12]]], [[[13], [14], [15]], [[16], [17], [18]]]])
arr4.shape

(3, 2, 3, 1)

Чтобы не исхищряться и не смотреть на длину кортежа, получаемого при использовании метода shape лучше использовать метод **ndim**.

In [13]:
arr4 = np.array([[[[1], [2], [3]], [[4], [5], [6]]], [[[7], [8], [9]], [[10], [11], [12]]], [[[13], [14], [15]], [[16], [17], [18]]]])
arr4.ndim

4

In [14]:
arr4.ndim == len(arr4.shape)

True

*P.S. Опытный читатель, знакомый с 1 курсом линейной алгебры поймёт, что ndim - number of dimensions - dimension - размерность. В контексте линейной алгебры обычно говорят про размерность пространства и обозначают это, как dim(L)*

## Как создать нулевую и единичную матрицу? zeros() ones()

Для создания массива из нулей достаточно прописать количество нулей, которое желает пользователь. Используем функцию **zeros()**.

In [15]:
zero_array = np.zeros(5)
zero_array

array([0., 0., 0., 0., 0.])

<b>Нулева́я матрица</b> — это матрица, размера m × n, все элементы которой равны нулю.

Для её создания воспользуемся функцией zeros(), но в качестве аргумента передадим ей кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов.

In [16]:
zero_matrix = np.zeros((2, 3))  # 2 строки и 3 столбца
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

Для создания массива из единиц достаточно прописать количество единиц, которое желает пользователь. Используем функцию **ones()**.

In [17]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

<b>Единичная матрица</b> — это матрица, размера m × n, все элементы которой равны одному.

Для её создания воспользуемся функцией ones(), но в качестве аргумента передадим ей кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов.

In [18]:
ones_matrix = np.ones((2, 3))  # 2 строки и 3 столбца
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.]])

На самом деле можно в кортеж передавать и больше чисел, но это слишком сложно для понимания на визуальном уровне.

## Как заполнить массив/матрицу произвольными значениями? full()

Прочитав предыдущий пункт, у многих закономерно возник вопрос: "*А как заполнить массив произвольными значениями?*"

Легко, используем функцию **full()**. В качестве первого аргумента передадим размер, а в качестве второго - то, чем будем заполнять массив.

In [19]:
array_full_of_fives = np.full(10, 5)
array_full_of_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

В случае, если мы захотим создать матрицу, то в качестве первого аргумента передадим кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов.

In [20]:
matrix_full_of_nines = np.full((4, 5), 9)  # 4 строки и 5 столбцов
matrix_full_of_nines

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

## Как создать массив, который будет заполнен значениями от 0 до N? arange()

Функция **arange()**. По сути тот же range() только для массивов в numpy.

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Точно так же, как и в range(), в **arange()** можно задавать ```(start, finish, step)```.

In [22]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

# Lesson02

## Как задать тип данных? dtype astype()

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

А что если я хочу, чтобы у меня были не целые числа, а с плавающей запятой? Тогда нужно дописать параметр **dtype=**.

In [24]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

А что если у нас уже есть массив, и мы хотим, чтобы все значения в нём снова стали *int*?
Для этого существует функция **astype()**. В аргумент функции передаётся тот тип данных, который мы желаем.

In [25]:
arr = arr.astype(np.int32)
arr

array([1, 2, 3, 4, 5], dtype=int32)

<b>*Важное замечание!*</b> Сама по себе функция *astype()* не меняет значение массива, а возвращает его копию с изменённым типом данных, поэтому нужно куда-то сохранять копию массива.

In [26]:
arr.astype(np.float64)
arr

array([1, 2, 3, 4, 5], dtype=int32)

Если вы поменяете тип данных с **float_ на int_**, то numpy отрежет десятичную часть от каждого числа и оставит только целую. В целом, нормальное и типичное поведение для питона.

In [27]:
arr = np.array([1.01, 9.99, 4.5, 6.45, 7.8,])
arr

array([1.01, 9.99, 4.5 , 6.45, 7.8 ])

In [28]:
arr = arr.astype(np.int32)
arr

array([1, 9, 4, 6, 7], dtype=int32)

## Арифметические операции с массивами

В отличие от списков в питоне, арифметические операции касательно массивов работают иначе. Все ниже перечисленные операции показаны на массивах, но матрицах тоже работают.

**Умножение**

In [29]:
lst = [1, 2, 3, 4]
lst * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [30]:
arr = np.array([1, 2, 3, 4])
arr * 2

array([2, 4, 6, 8])

In [31]:
arr * arr

array([ 1,  4,  9, 16])

**Сложение и вычитание**

In [32]:
arr + 10

array([11, 12, 13, 14])

In [33]:
10 - arr

array([9, 8, 7, 6])

**Деление**

In [34]:
arr / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
arr // 2

array([0, 1, 1, 2])

In [36]:
arr % 2

array([1, 0, 1, 0])

**Возведение в степень**

In [37]:
arr ** 3

array([ 1,  8, 27, 64])

In [38]:
arr ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

## Сравнение массивов

Numpy сравнивает массивы поэлементно

In [39]:
#  Резульаты измерений температуры в 1-й и 2-й дни
first_day = np.array([36.6, 36.5, 36.8])
second_day = np.array([36.6, 36.6, 36.6])
first_day > second_day

array([False, False,  True])

## Срезы

Срезы в numpy делаются абсолютно так же, как при работе со списками в python при помощи ```[start:finish:step]```.

In [40]:
arr = np.arange(10)
first_half = arr[:5]
second_half = arr[5:]
first_half, second_half

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

При использовании срезов, если границы выходят за размеров массива, то ошибки ```IndexError``` не будет возникать. Вместо этого будет взят максимально возможный срез в данной ситуации.

In [41]:
x = arr[0:200]  # явно выходим за  границы массива
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***Важный момент!*** Если мы захотим переприсвоить значение среза, то изменится изначальный массив.

In [42]:
first_half[0] = 100
second_half[1] = 101
arr

array([100,   1,   2,   3,   4,   5, 101,   7,   8,   9])

Что же делать, чтобы изначальный массив не изменялся? Читаем следующий блок ;)

## Как создать копию массива? copy()

Чтобы создать копию массива, достаточно использовать функцию **copy()**.

In [43]:
arr = np.arange(10)
first_half = arr[:5].copy()
second_half = arr[5:].copy()
first_half, second_half

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [44]:
first_half[0] = 100
second_half[1] = 101
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Мы изменили значение **копии** среза, а не сам срез, поэтому изначальный массив не поменялся.

# Lesson03

## Индексация двумерных массивов

К элементам двумерного массива мы можем обращаться как мы обращаемся к двумерным спискам, но есть более короткая запись. Numpy позволяет в одних квадратных скобках через запятую указать нужные нам индексы.

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
elem_1 = arr[1][1]
elem_2 = arr[1, 1]
elem_1 == elem_2

np.True_

Если вытаскивать строки и отдельные элементы довольно легко, то как нам вытащить столбцы?

Для этого мы у всего у массива возьмём по нулевому элементу. То есть двоеточие говорит нам о том, что бы берём все строки, а 0 о том, что у каждой строки мы берём нулевой элемент.

In [46]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [47]:
arr2[:, 0]

array([ 1,  5,  9, 13, 17])

Что примечательно, многие из читающих могут подумать, а почему мы не можем написать просто ```arr2[:][0]```?

In [48]:
arr2[:][0]

array([1, 2, 3, 4])

Подвох в том, что это особенность синтаксиса numpy. Конструкция ```arr2[:, 0]``` выполняется построчно, а ```arr2[:][0]``` - нет.

In [49]:
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [50]:
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

По примерам выше уже можно было понять, что общий синтаксис выглядить следующим образом:  
**```arr[срез по нужным строкам, срез по нужным стобцам]```**

## Фильтрация с помощью булевой маски

**Булева маска** - это массив из значений True и False. Каждый элемент проходит фильтрацию через булеву маску и распределяется в зависимости от значения маски:  
*  Если на той же позиции в маске стоит значение True, элемент добавляется в итоговый массив
*  Если на позиции стоит значение False, то элемент не будет включен в итоговый массив

In [51]:
arr = np.arange(10)
mask = np.array([True, True, True, False, False, False, False, False, True, True])
arr[mask]

array([0, 1, 2, 8, 9])

**Создание маски по условию**

Чтобы применить булеву маску к исходному массиву, достаточно подставить ее в качестве индекса.

In [52]:
compare_mask = arr < 3
compare_mask

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [53]:
arr[compare_mask]

array([0, 1, 2])

Чаще всего мы просто сразу пишем условие в квадратных скобках.

In [54]:
arr[arr > 5]

array([6, 7, 8, 9])

**Инверсия булевого массива**

Если мы захотим в маске поменять все значения с True на False, а с False на True, то нужно сделать инверсию маски. Для этого существует специальный символ тильда ```~```.

In [55]:
mask = np.array([True, False, False, True])
~mask

array([False,  True,  True, False])

**Алгебра логики булевых массивов**

In [56]:
mask_1 = np.array([True, False, False])
mask_2 = np.array([True, True, False])

*Логическое И(&)*

In [57]:
mask_1 & mask_2

array([ True, False, False])

*Логическое ИЛИ(|)*

In [58]:
mask_1 | mask_2

array([ True,  True, False])

## Прихотливая индексация

In [59]:
arr = np.array([
               [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16],
               [17, 18, 19, 20]
              ])

Интересное наблюдение: ```arr[[0, 2], :]``` и ```arr[[0, 2]]``` дают одинаковый вывод, порядок строк не важен.

In [60]:
arr[[0, 2], :] == arr[[0, 2]]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
arr[[4, 1]]

array([[17, 18, 19, 20],
       [ 5,  6,  7,  8]])

Аналогично работает и с колонками. Допустим, что мы хотим вытащить 2 и 3 столбец, причем поменять их местами.

In [62]:
arr[:, [2, 1]]

array([[ 3,  2],
       [ 7,  6],
       [11, 10],
       [15, 14],
       [19, 18]])

**Задача.** На вход функции подается двумерный массив: доработайте функцию так, чтобы она вернула значения, которые лежат на главной диагонали. Значения должны быть в одномерном массиве.

In [63]:
def solution(arr):
    arr = arr[range(5), range(5)]
    return arr

## Преобразование одномерного массива в двумерный и наоборот. reshape()

Чтобы преобразовать одномерный массив в двумерный существует функция **reshape()**. В качестве аргумента ей передаётся кортеж ```(m, n)```, где m - количество строк, а n - количество столбцов.

In [64]:
arr = np.arange(50)
arr.reshape((5, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Чтобы преобразовать двумерный массив в одномерный, в качестве аргумента в reshape() передаётся -1.

In [66]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

*Функция reshape() именяет исходный массив, а не делает его копию.*

# Lesson04